# TLS mode for this host.
# To enable Certbot/Letâ€™s Encrypt, set `tuxedovpn_tls_mode: "certbot"`.
tuxedovpn_tls_mode: "selfsigned" # selfsigned | certbot
tuxedovpn_acme_challenge: "dns" # dns | http | http_webroot
tuxedovpn_acme_dns_provider: "cloudflare"
vpn_domain: "vpn-02.example.com"
vpn_network_address: "10.66.2.0"
vpn_network_prefix_length: 24

# ocserv camouflage (example value; set something unique per host)
vpn_camouflage_secret_override: "change_me_camouflage_vpn_02"
